language: c
os: linux
dist: bionic
sudo: false
addons:
  apt:
    packages:
      - emacs
      - gnutls-bin
      - ca-certificates
install:
  - ln -sf $PWD $HOME/.emacs.d
script:
  - emacs --version
  - |
    emacs \
      --debug-init \
      --batch \
      --eval='(load-file "$HOME/.emacs.d/init.el")' \
      --eval='(magit-status)' \
      --kill
