language: c
os: linux
dist: bionic
sudo: false
addons:
  apt:
    sources:
      - sourceline: 'ppa:kelleyk/emacs'
    packages:
      - emacs27
      - gnutls-bin
      - ca-certificates
install:
  - ln -sf $PWD $HOME/.emacs.d
script:
  - emacs27 --version
  - |
    emacs27 \
      --debug-init \
      --batch \
      --eval='(load-file "$HOME/.emacs.d/early-init.el")(load-file "$HOME/.emacs.d/init.el")' \
      --eval='(magit-status)' \
      --kill
