name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: 0 7 1 * *
jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: purcell/setup-emacs@master
        with:
          version: 27.1
      - name: Execute magit-status
        run: |
          ln -sf $PWD $HOME/.emacs.d
          emacs \
            --debug-init \
            --batch \
            --eval='(load-file "$HOME/.emacs.d/early-init.el")' \
            --eval='(load-file "$HOME/.emacs.d/init.el")' \
            --eval='(magit-status)' \
            --kill
